## numpy

In [2]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [6]:
a

array([1, 2, 3])

In [7]:
# dtype
# apni pasand ke datatype ka aaray banana ho toh
b = np.array([1,2,0] ,dtype = bool)

In [8]:
b

array([ True,  True, False])

In [9]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
# with shope
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])